version: 2.1

jobs:
  build:
    working_directory: /
    docker:
      - image: alpine
    steps:
      - run: echo Helloworld
  test:
    working_directory: /
    docker:
      - image: "alpine"
    steps:
      - run: echo "Hello world this is test build"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build